version: "3.3"

services:
    gunicorn: 
        restart: always
        container_name: prod_gunicorn_repdoc
        build:
        context: .
        dockerfile: ./Dockerfile
        expose:
        - "8001"
        volumes:
        - .:/code
        - ./staticfiles:/code/staticfiles
        - ./database:/code/database
        command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn transf.wsgi:application -b 0.0.0.0:8001 --workers 3"
    nginx:
        restart: always
        container_name: prod_nginx_repdoc
        image: nginx:latest
        ports:
        - "80:82"
        volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./staticfiles:/code/staticfiles
        depends_on:
        - gunicorn